/**
 * Serializes an ltng-ui DOM node or plain object into a deterministic HTML-like string.
 * Used for snapshot testing.
 */
export function snapshotSerializeNode(node, indent = '') {
  if (node === null || node === undefined) return '';
  if (typeof node !== 'object') return String(node);
  if (Array.isArray(node)) {
    return node.map(n => snapshotSerializeNode(n, indent)).join('\n');
  }

  // Handle TextNodes (real DOM nodeType 3, or mock-dom.js TextNode which lacks tagName)
  if (node.nodeType === 3 || (!node._tag && !node.tagName && node.textContent !== undefined)) {
    return indent + String(node.nodeValue || node.textContent);
  }

  const tag = (node._tag || node.tagName || 'node').toLowerCase();
  
  // Extract attributes: Handle DOM NamedNodeMap, mock-dom.js object, or setup.mjs attrs object
  let rawAttrs = node.attrs || {};
  if (node.attributes) {
    if (typeof node.attributes.length === 'number') {
      rawAttrs = {};
      for (let i = 0; i < node.attributes.length; i++) {
          const attr = node.attributes[i];
          rawAttrs[attr.name] = attr.value;
      }
    } else {
      rawAttrs = { ...node.attributes };
    }
  }
  
  // Sort attributes for deterministic output
  const attrKeys = Object.keys(rawAttrs).sort();
  const attrString = attrKeys.map(k => {
      // Strip potentially randomly generated id UUIDs dynamically generated by ltng-ui fallback
      // This ensures snapshots remain deterministic between runs.
      if (k === 'id' && /^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(rawAttrs[k])) {
          return ` ${k}="[uuid-v7]"`;
      }
      return ` ${k}="${rawAttrs[k]}"`
  }).join('');
  
  // Extract children: Handle DOM childNodes vs mock children array
  let childList = node.children || [];
  if (childList.length === 0 && node.childNodes) {
      childList = Array.from(node.childNodes);
  }
  
  if (childList.length === 0) {
    return `${indent}<${tag}${attrString} />`;
  }
  
  const childrenStr = childList.map(c => snapshotSerializeNode(c, indent + '  ')).join('\n');
  return `${indent}<${tag}${attrString}>\n${childrenStr}\n${indent}</${tag}>`;
}
